[build]
target = "x86_64-unknown-linux-gnu"

[target.'cfg(target_os = "linux")']
# '-Zlocation-detail=none' 对降低编译产物大小没作用的样子
# '-C target-cpu=native' 对降低编译产物大小没作用的样子
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "force-frame-pointers=yes"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort"]
