[build]
target = "x86_64-unknown-linux-gnu"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "force-frame-pointers=yes"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
